
name: Automated Roslyn Version Bump

on:
  workflow_dispatch:
jobs:
  bump-roslyn:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install Microsoft.RoslynTools
        run: |
            dotnet tool install Microsoft.RoslynTools --prerelease --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json --tool-path ./.config/dotnet-tools || echo "Microsoft.RoslynTools already installed"

     

      - name: Run pr-finder
        run: |
            dotnet tool run roslyn-tools pr-finder -h


      
