name: Roslyn Version Bump

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Install roslyn-tools
        run: |
          FEED="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json"
          dotnet tool install -g Microsoft.RoslynTools --prerelease --add-source "$FEED"
          echo "$HOME/.dotnet/tools" >> "$GITHUB_PATH"

      - name: Clone roslyn & compute range
        id: sha
        run: |
          set -euo pipefail
          git clone --no-tags --depth 120 https://github.com/dotnet/roslyn.git roslyn
          END=$(git -C roslyn rev-parse HEAD)
          if [ -f .github/roslyn-last-sha.txt ]; then
            START=$(cat .github/roslyn-last-sha.txt)
            echo "Using stored start commit: $START"
          else
            START=$(git -C roslyn rev-list --max-count=2 HEAD | tail -n1 || git -C roslyn rev-parse HEAD)
            echo "Derived start commit: $START"
          fi
          if ! git -C roslyn cat-file -e "$START^{commit}" 2>/dev/null; then
            echo "Start commit $START not in shallow clone; fetching it";
            git -C roslyn fetch --no-tags origin "$START" || true
          fi
          echo "start=$START" >> $GITHUB_OUTPUT
          echo "end=$END" >> $GITHUB_OUTPUT
          if [ "$START" = "$END" ]; then echo "no_change=true" >> $GITHUB_OUTPUT; fi
          echo "End commit: $END"

      - name: Stop if no new commit
        if: steps.sha.outputs.no_change == 'true'
        run: echo "No new Roslyn commit since last run."

      - name: Auth settings
        if: steps.sha.outputs.no_change != 'true'
        run: |
          mkdir -p $HOME/.roslyn-tools
          JSON=$(printf '{"GitHubToken":"%s","DevDivAzureDevOpsToken":"","DncEngAzureDevOpsToken": ""}' "${{ secrets.GITHUB_TOKEN }}")
          printf '%s' "$JSON" | base64 | tr -d '\n' > $HOME/.roslyn-tools/settings

      - name: Generate PR list (label filtered)
        if: steps.sha.outputs.no_change != 'true'
        id: changelog
        env:
          LABEL: vscode
        run: |
          set -euo pipefail
          START="${{ steps.sha.outputs.start }}"
          END="${{ steps.sha.outputs.end }}"
          CMD=(roslyn-tools pr-finder -s "$START" -e "$END" --format changelog)
          if [ -n "${LABEL:-}" ]; then
            CMD+=(--label "$LABEL")
          fi
          echo "Running: ${CMD[*]}";
          if OUTPUT=$("${CMD[@]}" 2>err.log); then
            # Success path
            if [ -z "$OUTPUT" ]; then
              if [ -n "${LABEL:-}" ]; then
                echo "::notice::No PRs with label '$LABEL' in $START..$END. Trying without label.";
                if OUTPUT_ALL=$(roslyn-tools pr-finder -s "$START" -e "$END" --format changelog 2>>err.log); then
                  if [ -z "$OUTPUT_ALL" ]; then
                    echo "(no matching PRs)" > pr-changelog.txt
                  else
                    printf "%s\n" "$OUTPUT_ALL" > pr-changelog.txt
                  fi
                else
                  rc=$?
                  echo "::warning::Fallback pr-finder failed with exit code $rc";
                  echo "(pr-finder failed)" > pr-changelog.txt
                fi
              else
                echo "(no matching PRs)" > pr-changelog.txt
              fi
            else
              printf "%s\n" "$OUTPUT" > pr-changelog.txt
            fi
          else
            rc=$?
            if [ ! -s err.log ]; then
              echo "::notice::pr-finder exited $rc with no stderr; assuming no matches.";
              echo "(no matching PRs)" > pr-changelog.txt
            else
              echo "::warning::pr-finder primary call failed (exit $rc)";
              echo "---- pr-finder stderr ----"; (sed 's/^/stderr: /' err.log || true); echo "--------------------------";
              echo "(pr-finder failed)" > pr-changelog.txt
            fi
          fi
          if [ -s err.log ]; then
            echo "---- pr-finder stderr summary ----"; (sed 's/^/stderr: /' err.log || true); echo "----------------------------------";
          fi

      - name: Update CHANGELOG
        if: steps.sha.outputs.no_change != 'true'
        run: |
          set -euo pipefail
          DATE=$(date -u +%Y-%m-%d)
          RANGE_HEADER="### Roslyn changes (${DATE})"
          DIFF_URL="https://github.com/dotnet/roslyn/compare/${{ steps.sha.outputs.start }}...${{ steps.sha.outputs.end }}?w=1"
          { echo "$RANGE_HEADER"; echo; echo "Range: ${{ steps.sha.outputs.start }}...${{ steps.sha.outputs.end }}"; echo "Diff: $DIFF_URL"; echo; echo "#### PRs"; echo; cat pr-changelog.txt; echo; } | cat - CHANGELOG.md 2>/dev/null > _tmp && mv _tmp CHANGELOG.md
          echo "Changelog updated."

      - name: Store last processed commit
        if: steps.sha.outputs.no_change != 'true'
        run: echo "${{ steps.sha.outputs.end }}" > .github/roslyn-last-sha.txt

      - name: Cleanup clone
        if: steps.sha.outputs.no_change != 'true'
        run: rm -rf roslyn || true

      - name: Create PR
        if: steps.sha.outputs.no_change != 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: roslyn-changes/${{ steps.sha.outputs.end }}
          commit-message: "Roslyn changes: ${{ steps.sha.outputs.start }}...${{ steps.sha.outputs.end }}"
          title: "Roslyn changes: ${{ steps.sha.outputs.end }}"
          body: |
            Automated Roslyn commit-range changelog.
            Range: `${{ steps.sha.outputs.start }}` ... `${{ steps.sha.outputs.end }}`
            Label filter: vscode
            See CHANGELOG.md for details.