name: Roslyn PR Finder

on:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  pr-finder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET (9)
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Install roslyn-tools
        run: |
          set -euo pipefail
          FEED="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json"
          dotnet tool install -g Microsoft.RoslynTools --prerelease --add-source "$FEED"
          echo "$HOME/.dotnet/tools" >> "$GITHUB_PATH"

      - name: Determine commit range
        id: range
        run: |
          set -euo pipefail
          mkdir -p .github
          git clone --depth 2 https://github.com/dotnet/roslyn.git roslyn-temp
          END=$(git -C roslyn-temp rev-parse HEAD)
          if [ -f .github/roslyn-last-sha.txt ]; then
            START=$(cat .github/roslyn-last-sha.txt)
          else
            START=$(git -C roslyn-temp rev-parse HEAD~1 || echo "$END")
          fi
          echo "start_sha=$START" >> $GITHUB_OUTPUT
          echo "end_sha=$END" >> $GITHUB_OUTPUT

      - name: Write settings (GitHub token)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          mkdir -p "$HOME/.roslyn-tools"
          JSON=$(printf '{"GitHubToken":"%s","DevDivAzureDevOpsToken":"","DncEngAzureDevOpsToken":""}' "$GITHUB_TOKEN")
          printf '%s' "$JSON" | base64 | tr -d '\n' > "$HOME/.roslyn-tools/settings"

      - name: Run pr-finder
        env:
          START: ${{ steps.range.outputs.start_sha }}
          END: ${{ steps.range.outputs.end_sha }}
        run: |
          set -euo pipefail
          roslyn-tools pr-finder -s "$START" -e "$END" --format changelog > pr-changelog.txt || {
            echo "[View Diff](https://github.com/dotnet/roslyn/compare/$START...$END?w=1)" > pr-changelog.txt
          }
          head -n 50 pr-changelog.txt || true

      - name: Save end SHA
        run: |
          echo "${{ steps.range.outputs.end_sha }}" > .github/roslyn-last-sha.txt
          echo "Saved: $(cat .github/roslyn-last-sha.txt)"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pr-changelog
          path: pr-changelog.txt