name: Roslyn Version Bump

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:
    inputs:
      roslyn_build_id:
        description: 'Specific Roslyn build ID (optional)'
        required: false
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Install tools
        shell: bash
        run: |
          # Install roslyn-tools
          FEED="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json"
          dotnet tool install -g Microsoft.RoslynTools --prerelease --add-source "$FEED"
          echo "$HOME/.dotnet/tools" >> "$GITHUB_PATH"
          
          # Install jq for JSON parsing
          sudo apt-get update && sudo apt-get install -y jq

      - name: Get current Roslyn SHA from package
        id: current
        shell: bash
        run: |
          set -euo pipefail
          
          # Read current version from package.json
          CURRENT_VERSION=$(jq -r '.defaults.roslyn // empty' package.json)
          
          if [ -z "$CURRENT_VERSION" ]; then
            echo "Error: Could not find roslyn version in package.json"
            exit 1
          fi
          
          echo "Current Roslyn version: $CURRENT_VERSION"
          
          # Download the NuGet package and extract commit SHA from .nuspec file
          
          TEMP_DIR=$(mktemp -d)
          cd "$TEMP_DIR"
          
          # The package name used in vscode-csharp
          PACKAGE_NAME="microsoft.codeanalysis.common"
          
          # Download from dotnet-tools feed (where Roslyn packages are published)
          echo "Downloading from dotnet-tools feed..."
          DOTNET_TOOLS_FEED="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/flat2"
          PACKAGE_URL="$DOTNET_TOOLS_FEED/$PACKAGE_NAME/$CURRENT_VERSION/$PACKAGE_NAME.$CURRENT_VERSION.nupkg"
          
          if ! curl -f -L -o package.nupkg "$PACKAGE_URL"; then
            echo "Error: Could not download package $PACKAGE_NAME version $CURRENT_VERSION"
            echo "For testing, using placeholder SHA"
            START_SHA="0000000000000000000000000000000000000000"
            echo "start=$START_SHA" >> $GITHUB_OUTPUT
            cd - >/dev/null
            rm -rf "$TEMP_DIR"
            exit 0
          fi
          
          echo "Package downloaded successfully"
          
          # Extract the package
          unzip -q package.nupkg
          
          # Find the .nuspec file (following createTagsTasks.ts logic)
          NUSPEC_FILE=$(find . -name "*.nuspec" -type f | head -n1)
          
          if [ -z "$NUSPEC_FILE" ]; then
            echo "Error: No .nuspec file found in package"
            exit 1
          fi
          
          echo "Found nuspec file: $NUSPEC_FILE"
          
          # Extract commit SHA from .nuspec file using the same regex pattern as createTagsTasks.ts
          # Looking for: repository type="git" url="..." commit="SHA"
          START_SHA=$(grep -oP 'repository[^>]*commit="\K[a-f0-9]{40}' "$NUSPEC_FILE" | head -n1 || echo "")
          
          if [ -z "$START_SHA" ]; then
            echo "Warning: Could not extract commit SHA from nuspec file"
            cat "$NUSPEC_FILE" | grep -i repository || echo "No repository element found"
            echo "Using placeholder SHA for testing"
            START_SHA="0000000000000000000000000000000000000000"
          fi
          
          cd - >/dev/null
          rm -rf "$TEMP_DIR"
          
          # Validate SHA format
          if ! echo "$START_SHA" | grep -qE '^[a-f0-9]{40}$'; then
            echo "Warning: Invalid SHA format: $START_SHA"
            START_SHA="0000000000000000000000000000000000000000"
          fi
          
          echo "start=$START_SHA" >> $GITHUB_OUTPUT
          echo "Current Roslyn SHA from nuspec: $START_SHA"

      - name: Get latest Roslyn build from Azure DevOps
        id: latest
        shell: bash
        run: |
          set -euo pipefail
          
          # Get latest Roslyn version from official build pipeline's AssetManifests
          echo "Getting latest Roslyn build from Azure DevOps..."
          
          # The dotnet-roslyn-official pipeline is in the internal project
          # But we can access its builds via the public API endpoint
          AZDO_ORG="https://dev.azure.com/dnceng"
          
          # First, try to get the latest build from the dotnet-roslyn CI feed
          # This feed aggregates builds from various pipelines
          echo "Querying for latest Roslyn build..."
          
          # Use the public Roslyn builds endpoint
          # The builds are accessible without auth even though they're in internal project
          BUILD_URL="https://dev.azure.com/dnceng/public/_apis/build/builds?definitions=15&branchName=refs/heads/main&\$top=5&api-version=7.0"
          
          # Get recent builds and find one with artifacts
          BUILDS=$(curl -s "$BUILD_URL")
          BUILD_ID=""
          
          # Try to find a build with artifacts
          for id in $(echo "$BUILDS" | jq -r '.value[].id'); do
            ARTIFACT_CHECK="https://dev.azure.com/dnceng/public/_apis/build/builds/$id/artifacts?api-version=7.0"
            if curl -s "$ARTIFACT_CHECK" | jq -e '.count > 0' >/dev/null 2>&1; then
              BUILD_ID="$id"
              echo "Found build with artifacts: $BUILD_ID"
              break
            fi
          done
          
          # If no builds found in public, we need to use a different approach
          # Query the NuGet feed for the latest package and extract metadata from it
          if [ -z "$BUILD_ID" ]; then
            echo "No public builds found, querying NuGet feed for latest package..."
            
            # Get the latest version from the dotnet-tools feed package index
            PACKAGE_NAME="microsoft.codeanalysis.common"
            PACKAGE_INDEX="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/flat2/$PACKAGE_NAME/index.json"
            
            # Get all versions and pick the latest
            VERSIONS=$(curl -s "$PACKAGE_INDEX" | jq -r '.versions[]' 2>/dev/null || echo "")
            
            if [ -z "$VERSIONS" ]; then
              # Try dotnet8 feed
              PACKAGE_INDEX="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/flat2/$PACKAGE_NAME/index.json"
              VERSIONS=$(curl -s "$PACKAGE_INDEX" | jq -r '.versions[]' 2>/dev/null || echo "")
            fi
            
            # Get the latest prerelease version
            VERSION=$(echo "$VERSIONS" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+-' | tail -n1)
            
            if [ -z "$VERSION" ]; then
              echo "Error: Could not find any Roslyn versions in feed"
              VERSION="5.0.0-dev"
            fi
            
            echo "Latest version from feed: $VERSION"
            
            # Download the package to get commit SHA
            TEMP_DIR=$(mktemp -d)
            cd "$TEMP_DIR"
            
            DOTNET_TOOLS_FEED="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/flat2"
            PACKAGE_URL="$DOTNET_TOOLS_FEED/$PACKAGE_NAME/$VERSION/$PACKAGE_NAME.$VERSION.nupkg"
            
            END_SHA=""
            if curl -f -L -o package.nupkg "$PACKAGE_URL" 2>/dev/null; then
              unzip -q package.nupkg
              NUSPEC_FILE=$(find . -name "*.nuspec" -type f | head -n1)
              if [ -n "$NUSPEC_FILE" ]; then
                END_SHA=$(grep -oP 'repository[^>]*commit="\K[a-f0-9]{40}' "$NUSPEC_FILE" | head -n1 || echo "")
              fi
            fi
            
            cd - >/dev/null
            rm -rf "$TEMP_DIR"
            
            # If still no SHA, get from GitHub
            if [ -z "$END_SHA" ]; then
              echo "Getting latest commit from GitHub..."
              END_SHA=$(curl -s "https://api.github.com/repos/dotnet/roslyn/commits/main" | jq -r '.sha // empty')
            fi
            
            echo "end=$END_SHA" >> $GITHUB_OUTPUT
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            echo "build_id=feed" >> $GITHUB_OUTPUT
            echo "build_url=https://github.com/dotnet/roslyn/commit/$END_SHA" >> $GITHUB_OUTPUT
            echo "build_number=$VERSION" >> $GITHUB_OUTPUT
            
          else
            # We found a build with artifacts, get its details
            BUILD_DETAILS=$(curl -s "https://dev.azure.com/dnceng/public/_apis/build/builds/$BUILD_ID?api-version=7.0")
            
            END_SHA=$(echo "$BUILD_DETAILS" | jq -r '.sourceVersion // empty')
            BUILD_NUMBER=$(echo "$BUILD_DETAILS" | jq -r '.buildNumber // empty')
            
            echo "Build commit: $END_SHA"
            echo "Build number: $BUILD_NUMBER"
            
            # Try to download AssetManifests artifact
            ARTIFACTS_URL="https://dev.azure.com/dnceng/public/_apis/build/builds/$BUILD_ID/artifacts?api-version=7.0"
            ARTIFACT_LIST=$(curl -s "$ARTIFACTS_URL")
            
            # Look for AssetManifests or any artifact with version info
            VERSION=""
            MANIFEST_URL=$(echo "$ARTIFACT_LIST" | jq -r '.value[] | select(.name | contains("Manifest")) | .resource.downloadUrl // empty' | head -n1)
            
            if [ -n "$MANIFEST_URL" ]; then
              TEMP_DIR=$(mktemp -d)
              cd "$TEMP_DIR"
              
              if curl -L -o manifest.zip "$MANIFEST_URL" 2>/dev/null && unzip -q manifest.zip 2>/dev/null; then
                XML_FILE=$(find . -name "*.xml" | head -n1)
                if [ -n "$XML_FILE" ]; then
                  VERSION=$(grep -oP 'Id="Microsoft\.CodeAnalysis[^"]*"[^>]*Version="\K[^"]+' "$XML_FILE" | head -n1)
                fi
              fi
              
              cd - >/dev/null
              rm -rf "$TEMP_DIR"
            fi
            
            # Fallback to construct version from build number
            if [ -z "$VERSION" ]; then
              VERSION="5.0.0-ci.$BUILD_NUMBER"
            fi
            
            echo "end=$END_SHA" >> $GITHUB_OUTPUT
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            echo "build_id=$BUILD_ID" >> $GITHUB_OUTPUT
            echo "build_url=https://dev.azure.com/dnceng/public/_build/results?buildId=$BUILD_ID" >> $GITHUB_OUTPUT
            echo "build_number=$BUILD_NUMBER" >> $GITHUB_OUTPUT
          fi
          
          echo "Latest Roslyn commit: $END_SHA"
          echo "Latest Roslyn version: $VERSION"
          
          if [ "${{ steps.current.outputs.start }}" = "$END_SHA" ]; then
            echo "no_change=true" >> $GITHUB_OUTPUT
            echo "No new commits to process"
          fi

      - name: Clone roslyn for PR finder
        if: steps.latest.outputs.no_change != 'true'
        shell: bash
        run: |
          git clone --no-tags --filter=blob:none --depth=500 https://github.com/dotnet/roslyn.git roslyn

      - name: Auth settings
        if: steps.latest.outputs.no_change != 'true'
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p "$HOME/.roslyn-tools"
          
          JSON=$(printf '{"GitHubToken":"%s","DevDivAzureDevOpsToken":"","DncEngAzureDevOpsToken":""}' "${{ secrets.GITHUB_TOKEN }}")
          printf '%s' "$JSON" | base64 | tr -d '\n' > "$HOME/.roslyn-tools/settings"

      - name: Generate PR list
        id: prs
        if: steps.latest.outputs.no_change != 'true'
        shell: bash
        run: |
          set -euo pipefail
          pushd roslyn >/dev/null
          
          # Run pr-finder with VSCode label only
          if OUTPUT=$(roslyn-tools pr-finder \
            -s "${{ steps.current.outputs.start }}" \
            -e "${{ steps.latest.outputs.end }}" \
            --format changelog \
            --label VSCode 2>/dev/null); then
            if [ -z "$OUTPUT" ]; then
              echo "(no PRs with required labels)" > ../pr-changelog.txt
            else
              printf "%s\n" "$OUTPUT" > ../pr-changelog.txt
            fi
          else
            echo "(pr-finder failed)" > ../pr-changelog.txt
          fi
          
          popd >/dev/null
          cat pr-changelog.txt
          
          if grep -qE '^\((no PRs|pr-finder failed)\)' pr-changelog.txt; then 
            echo "empty=true" >> $GITHUB_OUTPUT
          fi

      - name: Update CHANGELOG and package.json
        id: update
        if: steps.latest.outputs.no_change != 'true'
        uses: actions/github-script@v7
        env:
          ROSLYN_VER: ${{ steps.latest.outputs.version }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { readFile, writeFile } = require('fs/promises');
            
            const CHANGELOG = 'CHANGELOG.md';
            const PR_FILE = 'pr-changelog.txt';
            const roslynVer = process.env.ROSLYN_VER || 'unknown';
            
            core.info(`Updating with Roslyn version: ${roslynVer}`);
            
            // Update package.json
            try {
              const pkg = JSON.parse(await readFile('package.json', 'utf8'));
              if (!pkg.defaults) pkg.defaults = {};
              
              const oldVersion = pkg.defaults.roslyn;
              if (oldVersion !== roslynVer) {
                core.info(`Updating package.json: ${oldVersion} -> ${roslynVer}`);
                pkg.defaults.roslyn = roslynVer;
                await writeFile('package.json', JSON.stringify(pkg, null, 2) + '\n');
              }
            } catch (err) {
              core.setFailed(`Failed to update package.json: ${err.message}`);
              return;
            }
            
            // Load PR list
            let prLines = [];
            try {
              const prContent = await readFile(PR_FILE, 'utf8');
              prLines = prContent
                .split(/\r?\n/)
                .filter(l => l.trim().length && !l.includes('[View Complete Diff'))
                .map(l => l.startsWith('*') ? `  ${l}` : `  * ${l}`);
            } catch (err) {
              core.warning(`Could not read ${PR_FILE}: ${err.message}`);
            }
            
            // Update CHANGELOG
            const content = await readFile(CHANGELOG, 'utf8');
            const lines = content.split(/\r?\n/);
            
            // Find first section and existing bump line
            let bumpLineIndex = -1;
            let firstHeaderIndex = lines.findIndex(l => /^# /.test(l));
            let nextHeaderIndex = lines.findIndex((l, i) => i > firstHeaderIndex && /^# /.test(l));
            let sectionEnd = nextHeaderIndex > 0 ? nextHeaderIndex : lines.length;
            
            for (let i = firstHeaderIndex + 1; i < sectionEnd; i++) {
              if (/^\* Bump Roslyn to .* \(PR:/.test(lines[i])) {
                bumpLineIndex = i;
                break;
              }
            }
            
            if (bumpLineIndex === -1) {
              core.setFailed('Could not find existing Roslyn bump line');
              return;
            }
            
            // Update bump line
            lines[bumpLineIndex] = `* Bump Roslyn to ${roslynVer} (PR: [#TBD](TBD))`;
            
            // Insert PR lines
            let insertPoint = bumpLineIndex + 1;
            while (insertPoint < lines.length && lines[insertPoint].startsWith('  *')) {
              insertPoint++;
            }
            
            if (prLines.length > 0) {
              lines.splice(insertPoint, 0, ...prLines);
            }
            
            await writeFile(CHANGELOG, lines.join('\n'));
            core.info('Successfully updated CHANGELOG.md');

      - name: Create PR
        if: steps.latest.outputs.no_change != 'true'
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: roslyn-bump/${{ steps.latest.outputs.end }}
          commit-message: "Bump Roslyn to ${{ steps.latest.outputs.version }}"
          title: "Bump Roslyn to ${{ steps.latest.outputs.version }}"
          add-paths: |
            CHANGELOG.md
            package.json
          body: |
            Automated Roslyn version bump.
            
            **Version:** `${{ steps.latest.outputs.version }}`
            **Commit Range:** `${{ steps.current.outputs.start }}....${{ steps.latest.outputs.end }}`
            **Azure DevOps Build:** [${{ steps.latest.outputs.build_id }}](${{ steps.latest.outputs.build_url }})
            
            See CHANGELOG.md for included PRs.

      - name: Backfill PR link in CHANGELOG
        if: steps.cpr.outputs.pull-request-number && steps.latest.outputs.no_change != 'true'
        shell: bash
        run: |
          set -euo pipefail
          
          PR_URL="${{ steps.cpr.outputs.pull-request-url }}"
          PR_NUM="${{ steps.cpr.outputs.pull-request-number }}"
          BRANCH="roslyn-bump/${{ steps.latest.outputs.end }}"
          
          git fetch origin "$BRANCH" --depth=1
          git checkout "$BRANCH"
          
          # Replace TBD placeholders with actual PR number and URL
          sed -i "s|#TBD|#$PR_NUM|" CHANGELOG.md
          sed -i "s|(TBD)|($PR_URL)|" CHANGELOG.md
          
          if git diff --quiet; then
            echo "No placeholder replacement occurred."
            exit 0
          fi
          
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add CHANGELOG.md
          git commit -m "Backfill PR link #$PR_NUM"
          git push origin "$BRANCH"