name: Roslyn Version Bump

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:
    inputs:
      roslyn_build_id:
        description: 'Specific Roslyn build ID (optional)'
        required: false
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Install tools
        shell: bash
        run: |
          # Install roslyn-tools
          FEED="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json"
          dotnet tool install -g Microsoft.RoslynTools --prerelease --add-source "$FEED"
          echo "$HOME/.dotnet/tools" >> "$GITHUB_PATH"
          
          # Install jq for JSON parsing
          sudo apt-get update && sudo apt-get install -y jq

      - name: Get current Roslyn SHA from package
        id: current
        shell: bash
        run: |
          set -euo pipefail
          
          # Read current version from package.json
          CURRENT_VERSION=$(jq -r '.defaults.roslyn // empty' package.json)
          
          if [ -z "$CURRENT_VERSION" ]; then
            echo "Error: Could not find roslyn version in package.json"
            exit 1
          fi
          
          echo "Current Roslyn version: $CURRENT_VERSION"
          
          # Download the NuGet package and extract commit SHA from .nuspec file
          
          TEMP_DIR=$(mktemp -d)
          cd "$TEMP_DIR"
          
          # The package name used in vscode-csharp
          PACKAGE_NAME="microsoft.codeanalysis.common"
          
          # Download from dotnet-tools feed (where Roslyn packages are published)
          echo "Downloading from dotnet-tools feed..."
          DOTNET_TOOLS_FEED="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/flat2"
          PACKAGE_URL="$DOTNET_TOOLS_FEED/$PACKAGE_NAME/$CURRENT_VERSION/$PACKAGE_NAME.$CURRENT_VERSION.nupkg"
          
          if ! curl -f -L -o package.nupkg "$PACKAGE_URL"; then
            echo "Error: Could not download package $PACKAGE_NAME version $CURRENT_VERSION"
            echo "For testing, using placeholder SHA"
            START_SHA="0000000000000000000000000000000000000000"
            echo "start=$START_SHA" >> $GITHUB_OUTPUT
            cd - >/dev/null
            rm -rf "$TEMP_DIR"
            exit 0
          fi
          
          echo "Package downloaded successfully"
          
          # Extract the package
          unzip -q package.nupkg
          
          # Find the .nuspec file (following createTagsTasks.ts logic)
          NUSPEC_FILE=$(find . -name "*.nuspec" -type f | head -n1)
          
          if [ -z "$NUSPEC_FILE" ]; then
            echo "Error: No .nuspec file found in package"
            exit 1
          fi
          
          echo "Found nuspec file: $NUSPEC_FILE"
          
          # Extract commit SHA from .nuspec file using the same regex pattern as createTagsTasks.ts
          # Looking for: repository type="git" url="..." commit="SHA"
          START_SHA=$(grep -oP 'repository[^>]*commit="\K[a-f0-9]{40}' "$NUSPEC_FILE" | head -n1 || echo "")
          
          if [ -z "$START_SHA" ]; then
            echo "Warning: Could not extract commit SHA from nuspec file"
            cat "$NUSPEC_FILE" | grep -i repository || echo "No repository element found"
            echo "Using placeholder SHA for testing"
            START_SHA="0000000000000000000000000000000000000000"
          fi
          
          cd - >/dev/null
          rm -rf "$TEMP_DIR"
          
          # Validate SHA format
          if ! echo "$START_SHA" | grep -qE '^[a-f0-9]{40}$'; then
            echo "Warning: Invalid SHA format: $START_SHA"
            START_SHA="0000000000000000000000000000000000000000"
          fi
          
          echo "start=$START_SHA" >> $GITHUB_OUTPUT
          echo "Current Roslyn SHA from nuspec: $START_SHA"

      - name: Get latest Roslyn build from Azure DevOps
        id: latest
        shell: bash
        run: |
          set -euo pipefail
          
          # Get latest Roslyn version from NuGet feed directly
          echo "Getting latest Roslyn version from NuGet feed..."
          
          # Query the dotnet-tools feed for latest Microsoft.CodeAnalysis.Common package
          PACKAGE_NAME="microsoft.codeanalysis.common"
          FEED_URL="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json"
          
          # Get feed service index
          FEED_INDEX=$(curl -s "$FEED_URL")
          
          # Extract the SearchQueryService URL
          SEARCH_URL=$(echo "$FEED_INDEX" | jq -r '.resources[] | select(."@type" | contains("SearchQueryService")) | ."@id"' | head -n1)
          
          if [ -z "$SEARCH_URL" ]; then
            # Fallback to direct package index
            echo "Using direct package index..."
            PACKAGE_INDEX="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/flat2/$PACKAGE_NAME/index.json"
            VERSIONS=$(curl -s "$PACKAGE_INDEX" | jq -r '.versions[]' 2>/dev/null || echo "")
            
            if [ -z "$VERSIONS" ]; then
              # Try the dotnet8 feed as fallback
              PACKAGE_INDEX="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/flat2/$PACKAGE_NAME/index.json"
              VERSIONS=$(curl -s "$PACKAGE_INDEX" | jq -r '.versions[]' 2>/dev/null || echo "")
            fi
            
            # Get the latest version (last in the list, filtering prereleases)
            VERSION=$(echo "$VERSIONS" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+-' | tail -n1)
          else
            # Query for the package
            SEARCH_RESULT=$(curl -s "${SEARCH_URL}?q=$PACKAGE_NAME&prerelease=true&take=1")
            VERSION=$(echo "$SEARCH_RESULT" | jq -r '.data[0].version // empty')
          fi
          
          if [ -z "$VERSION" ]; then
            echo "Error: Could not get latest Roslyn version from feed"
            # Use a fallback - get latest from GitHub
            echo "Falling back to GitHub for latest version"
            VERSION="5.0.0-dev"
          fi
          
          echo "Latest Roslyn version from feed: $VERSION"
          
          # Now download this package to get the commit SHA
          TEMP_DIR=$(mktemp -d)
          cd "$TEMP_DIR"
          
          echo "Downloading package to extract commit SHA..."
          DOTNET_TOOLS_FEED="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/flat2"
          PACKAGE_URL="$DOTNET_TOOLS_FEED/$PACKAGE_NAME/$VERSION/$PACKAGE_NAME.$VERSION.nupkg"
          
          END_SHA=""
          if curl -f -L -o package.nupkg "$PACKAGE_URL" 2>/dev/null; then
            unzip -q package.nupkg
            NUSPEC_FILE=$(find . -name "*.nuspec" -type f | head -n1)
            if [ -n "$NUSPEC_FILE" ]; then
              END_SHA=$(grep -oP 'repository[^>]*commit="\K[a-f0-9]{40}' "$NUSPEC_FILE" | head -n1 || echo "")
              echo "Extracted commit SHA from package: $END_SHA"
            fi
          fi
          
          cd - >/dev/null
          rm -rf "$TEMP_DIR"
          
          # If we couldn't get SHA from package, get latest from GitHub
          if [ -z "$END_SHA" ] || [ "$END_SHA" = "null" ]; then
            echo "Getting latest commit from GitHub..."
            END_SHA=$(curl -s "https://api.github.com/repos/dotnet/roslyn/commits/main" | jq -r '.sha // empty')
            
            if [ -z "$END_SHA" ]; then
              echo "Error: Could not get latest commit SHA"
              exit 1
            fi
          fi
          
          echo "end=$END_SHA" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Latest Roslyn commit: $END_SHA"
          echo "Latest Roslyn version: $VERSION"
          
          # For build metadata, use GitHub commit URL
          echo "build_id=github" >> $GITHUB_OUTPUT
          echo "build_url=https://github.com/dotnet/roslyn/commit/$END_SHA" >> $GITHUB_OUTPUT
          echo "build_number=$VERSION" >> $GITHUB_OUTPUT
          
          if [ "${{ steps.current.outputs.start }}" = "$END_SHA" ]; then
            echo "no_change=true" >> $GITHUB_OUTPUT
            echo "No new commits to process"
          fi

      - name: Clone roslyn for PR finder
        if: steps.latest.outputs.no_change != 'true'
        shell: bash
        run: |
          git clone --no-tags --filter=blob:none --depth=500 https://github.com/dotnet/roslyn.git roslyn

      - name: Auth settings
        if: steps.latest.outputs.no_change != 'true'
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p "$HOME/.roslyn-tools"
          
          JSON=$(printf '{"GitHubToken":"%s","DevDivAzureDevOpsToken":"","DncEngAzureDevOpsToken":""}' "${{ secrets.GITHUB_TOKEN }}")
          printf '%s' "$JSON" | base64 | tr -d '\n' > "$HOME/.roslyn-tools/settings"

      - name: Generate PR list
        id: prs
        if: steps.latest.outputs.no_change != 'true'
        shell: bash
        run: |
          set -euo pipefail
          pushd roslyn >/dev/null
          
          # Run pr-finder with VSCode label only
          if OUTPUT=$(roslyn-tools pr-finder \
            -s "${{ steps.current.outputs.start }}" \
            -e "${{ steps.latest.outputs.end }}" \
            --format changelog \
            --label VSCode 2>/dev/null); then
            if [ -z "$OUTPUT" ]; then
              echo "(no PRs with required labels)" > ../pr-changelog.txt
            else
              printf "%s\n" "$OUTPUT" > ../pr-changelog.txt
            fi
          else
            echo "(pr-finder failed)" > ../pr-changelog.txt
          fi
          
          popd >/dev/null
          cat pr-changelog.txt
          
          if grep -qE '^\((no PRs|pr-finder failed)\)' pr-changelog.txt; then 
            echo "empty=true" >> $GITHUB_OUTPUT
          fi

      - name: Update CHANGELOG and package.json
        id: update
        if: steps.latest.outputs.no_change != 'true'
        uses: actions/github-script@v7
        env:
          ROSLYN_VER: ${{ steps.latest.outputs.version }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { readFile, writeFile } = require('fs/promises');
            
            const CHANGELOG = 'CHANGELOG.md';
            const PR_FILE = 'pr-changelog.txt';
            const roslynVer = process.env.ROSLYN_VER || 'unknown';
            
            core.info(`Updating with Roslyn version: ${roslynVer}`);
            
            // Update package.json
            try {
              const pkg = JSON.parse(await readFile('package.json', 'utf8'));
              if (!pkg.defaults) pkg.defaults = {};
              
              const oldVersion = pkg.defaults.roslyn;
              if (oldVersion !== roslynVer) {
                core.info(`Updating package.json: ${oldVersion} -> ${roslynVer}`);
                pkg.defaults.roslyn = roslynVer;
                await writeFile('package.json', JSON.stringify(pkg, null, 2) + '\n');
              }
            } catch (err) {
              core.setFailed(`Failed to update package.json: ${err.message}`);
              return;
            }
            
            // Load PR list
            let prLines = [];
            try {
              const prContent = await readFile(PR_FILE, 'utf8');
              prLines = prContent
                .split(/\r?\n/)
                .filter(l => l.trim().length && !l.includes('[View Complete Diff'))
                .map(l => l.startsWith('*') ? `  ${l}` : `  * ${l}`);
            } catch (err) {
              core.warning(`Could not read ${PR_FILE}: ${err.message}`);
            }
            
            // Update CHANGELOG
            const content = await readFile(CHANGELOG, 'utf8');
            const lines = content.split(/\r?\n/);
            
            // Find first section and existing bump line
            let bumpLineIndex = -1;
            let firstHeaderIndex = lines.findIndex(l => /^# /.test(l));
            let nextHeaderIndex = lines.findIndex((l, i) => i > firstHeaderIndex && /^# /.test(l));
            let sectionEnd = nextHeaderIndex > 0 ? nextHeaderIndex : lines.length;
            
            for (let i = firstHeaderIndex + 1; i < sectionEnd; i++) {
              if (/^\* Bump Roslyn to .* \(PR:/.test(lines[i])) {
                bumpLineIndex = i;
                break;
              }
            }
            
            if (bumpLineIndex === -1) {
              core.setFailed('Could not find existing Roslyn bump line');
              return;
            }
            
            // Update bump line
            lines[bumpLineIndex] = `* Bump Roslyn to ${roslynVer} (PR: [#TBD](TBD))`;
            
            // Insert PR lines
            let insertPoint = bumpLineIndex + 1;
            while (insertPoint < lines.length && lines[insertPoint].startsWith('  *')) {
              insertPoint++;
            }
            
            if (prLines.length > 0) {
              lines.splice(insertPoint, 0, ...prLines);
            }
            
            await writeFile(CHANGELOG, lines.join('\n'));
            core.info('Successfully updated CHANGELOG.md');

      - name: Create PR
        if: steps.latest.outputs.no_change != 'true'
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: roslyn-bump/${{ steps.latest.outputs.end }}
          commit-message: "Bump Roslyn to ${{ steps.latest.outputs.version }}"
          title: "Bump Roslyn to ${{ steps.latest.outputs.version }}"
          add-paths: |
            CHANGELOG.md
            package.json
          body: |
            Automated Roslyn version bump.
            
            **Version:** `${{ steps.latest.outputs.version }}`
            **Commit Range:** `${{ steps.current.outputs.start }}....${{ steps.latest.outputs.end }}`
            **Azure DevOps Build:** [${{ steps.latest.outputs.build_id }}](${{ steps.latest.outputs.build_url }})
            
            See CHANGELOG.md for included PRs.

      - name: Backfill PR link in CHANGELOG
        if: steps.cpr.outputs.pull-request-number && steps.latest.outputs.no_change != 'true'
        shell: bash
        run: |
          set -euo pipefail
          
          PR_URL="${{ steps.cpr.outputs.pull-request-url }}"
          PR_NUM="${{ steps.cpr.outputs.pull-request-number }}"
          BRANCH="roslyn-bump/${{ steps.latest.outputs.end }}"
          
          git fetch origin "$BRANCH" --depth=1
          git checkout "$BRANCH"
          
          # Replace TBD placeholders with actual PR number and URL
          sed -i "s|#TBD|#$PR_NUM|" CHANGELOG.md
          sed -i "s|(TBD)|($PR_URL)|" CHANGELOG.md
          
          if git diff --quiet; then
            echo "No placeholder replacement occurred."
            exit 0
          fi
          
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add CHANGELOG.md
          git commit -m "Backfill PR link #$PR_NUM"
          git push origin "$BRANCH"