name: Roslyn Version Bump

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Install roslyn-tools
        run: |
          FEED="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json"
          dotnet tool install -g Microsoft.RoslynTools --prerelease --add-source "$FEED"
          echo "$HOME/.dotnet/tools" >> "$GITHUB_PATH"

      - name: Get SHAs
        id: sha
        run: |
          set -euo pipefail
          echo "Cloning roslyn (shallow)..."
          git clone --no-tags --depth 10 https://github.com/dotnet/roslyn.git roslyn
          LATEST=$(git -C roslyn rev-parse HEAD)
          echo "Latest commit: $LATEST"
          if [ -f .github/roslyn-last-sha.txt ]; then
            LAST=$(cat .github/roslyn-last-sha.txt)
            echo "Found stored last sha: $LAST"
          else
            # Get the second commit we have in the shallow history (may be blank if only one commit was fetched)
            SECOND=$(git -C roslyn rev-list --max-count=2 HEAD | tail -n1 || true)
            if [ -n "$SECOND" ] && [ "$SECOND" != "$LATEST" ]; then
              LAST="$SECOND"
              echo "Derived previous commit from shallow history: $LAST"
            else
              LAST="$LATEST"
              echo "Only one commit available; using latest for last: $LAST"
            fi
          fi
          echo "latest=$LATEST" >> $GITHUB_OUTPUT
          echo "last=$LAST" >> $GITHUB_OUTPUT
          if [ "$LATEST" = "$LAST" ]; then echo "up_to_date=true" >> $GITHUB_OUTPUT; fi

      - name: Stop if up to date
        if: steps.sha.outputs.up_to_date == 'true'
        run: echo "No new commit"

      - name: Auth settings
        if: steps.sha.outputs.up_to_date != 'true'
        run: |
          mkdir -p $HOME/.roslyn-tools
          JSON=$(printf '{"GitHubToken":"%s","DevDivAzureDevOpsToken":"","DncEngAzureDevOpsToken":""}' "${{ secrets.GITHUB_TOKEN }}")
          printf '%s' "$JSON" | base64 | tr -d '\n' > $HOME/.roslyn-tools/settings

      - name: Generate changelog
        if: steps.sha.outputs.up_to_date != 'true'
        run: |
          roslyn-tools pr-finder -s "${{ steps.sha.outputs.last }}" -e "${{ steps.sha.outputs.latest }}" --format changelog > pr-changelog.txt || echo "[Diff](https://github.com/dotnet/roslyn/compare/${{ steps.sha.outputs.last }}...${{ steps.sha.outputs.latest }}?w=1)" > pr-changelog.txt
          head -n 30 pr-changelog.txt || true

      - name: Update files
        if: steps.sha.outputs.up_to_date != 'true'
        run: |
          echo "${{ steps.sha.outputs.latest }}" > roslyn-version.txt
          TITLE="## Roslyn Update ($(date -u +%Y-%m-%d))"
          DIFF="https://github.com/dotnet/roslyn/compare/${{ steps.sha.outputs.last }}...${{ steps.sha.outputs.latest }}?w=1"
          { echo "$TITLE"; echo "Latest: ${{ steps.sha.outputs.latest }}"; echo "Previous: ${{ steps.sha.outputs.last }}"; echo "Diff: $DIFF"; echo; cat pr-changelog.txt; echo; } | cat - CHANGELOG_ROSLYN.md 2>/dev/null > _tmp && mv _tmp CHANGELOG_ROSLYN.md
          echo "${{ steps.sha.outputs.latest }}" > .github/roslyn-last-sha.txt

      - name: Commit & PR
        if: steps.sha.outputs.up_to_date != 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: roslyn-bump/${{ steps.sha.outputs.latest }}
          commit-message: "Roslyn bump: ${{ steps.sha.outputs.latest }}"
          title: "Roslyn bump: ${{ steps.sha.outputs.latest }}"
          body: |
            Automated Roslyn bump.
            Latest: `${{ steps.sha.outputs.latest }}`
            Previous: `${{ steps.sha.outputs.last }}`
            Diff: https://github.com/dotnet/roslyn/compare/${{ steps.sha.outputs.last }}...${{ steps.sha.outputs.latest }}?w=1
            Review the added section in CHANGELOG_ROSLYN.md.

      - name: Upload changelog
        if: steps.sha.outputs.up_to_date != 'true'
        uses: actions/upload-artifact@v4
        with:
          name: roslyn-changelog
          path: |
            pr-changelog.txt
            CHANGELOG_ROSLYN.md
            roslyn-version.txt